# -*- coding: utf-8 -*-
"""СК_лаб2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-rpjKdxpTvIkff6wanWSDsIEO8C6Zi6m
"""

def shifr (key):
    f = open('Text')
    i=0
    Shifrotext=str()
    for char in f.read():
      if ord(char)>=1072 and ord(char)<=1072+31:
        Shifrotext=Shifrotext+str(chr((ord(char)-1072+ord(key[i])-1072)%32+1072))
        i=i+1
        if i>=len(key)-1:
          i=0
    return Shifrotext
    f.close()

def Indeks(Y):
  I=0
  for i in range(32):
    I=I+count_liters(Y)[i]*(count_liters(Y)[i]-1)
  I=I/ALL(Y)/(ALL(Y)-1)
  return I

def count_liters(Y):
  count=[ 0 for i in range(32)]
  for char in Y:
    if ord(char)>=1072 and ord(char)<=1072+31:
      count[ord(char)-1072]=count[ord(char)-1072]+1
  return count

def ALL(Y):
   All=0
   for char in Y:
     if ord(char)>=1072 and ord(char)<=1072+31:
        All=All+1
   return All

print(shifr('а'))
print(shifr('не'))
print(shifr('пол'))
print(shifr('стул'))
print(shifr('ручка'))
print(shifr('аксиоматический'))

print (Indeks(shifr('а')))
print (Indeks(shifr('не')))
print (Indeks(shifr('пол')))
print (Indeks(shifr('стул')))
print (Indeks(shifr('ручка')))
print (Indeks(shifr('вагоноопро')))
print (Indeks(shifr('вагоноопрок')))
print (Indeks(shifr('вагоноопроки')))
print (Indeks(shifr('вагоноопрокид')))
print (Indeks(shifr('вагоноопрокиды')))
print (Indeks(shifr('вагоноопрокидыв')))
print (Indeks(shifr('вагоноопрокидыва')))
print (Indeks(shifr('вагоноопрокидыват')))
print (Indeks(shifr('вагоноопрокидывате')))
print (Indeks(shifr('вагоноопрокидывател')))
print (Indeks(shifr('вагоноопрокидыватель')))

def reshifr19(Y):
    i=0
    r=19
    text=str()
    text0=str()
    text1=str()
    text2=str()
    text3=str()
    text4=str()
    text5=str()
    text6=str()
    text7=str()
    text8=str()
    text9=str()
    text10=str()
    text11=str()
    text12=str()
    text13=str()
    text14=str()
    text15=str()
    text16=str()
    text17=str()
    text18=str()
    for char in Y:
      if i==0:
        text0=text0+str(char)
      if i==1:
        text1=text1+str(char)
      if i==2:
        text2=text2+str(char)
      if i==3:
        text3=text3+str(char)
      if i==4:
        text4=text4+str(char)
      if i==5:
        text5=text5+str(char)
      if i==6:
        text6=text6+str(char)
      if i==7:
        text7=text7+str(char)
      if i==8:
        text8=text8+str(char)
      if i==9:
        text9=text9+str(char)
      if i==10:
        text10=text10+str(char)
      if i==11:
        text11=text11+str(char)
      if i==12:
        text12=text12+str(char)
      if i==13:
        text13=text13+str(char)
      if i==14:
        text14=text14+str(char)
      if i==15:
        text15=text15+str(char)
      if i==16:
        text16=text16+str(char)
      if i==17:
        text17=text17+str(char)
      if i==18:
        text18=text18+str(char)
      i=i+1
      if i==r:
        i=0
    k0=M(text0)
    k1=M(text1)
    k2=M(text2)
    k3=M(text3)
    k4=M(text4)
    k5=M(text5)
    k6=M(text6)
    k7=M(text7)
    k8=M(text8)
    k9=M(text9)
    k10=M(text10)
    k11=M(text11)
    k12=M(text12)
    k13=M(text13)
    k14=M(text14)
    k15=M(text15)
    k16=M(text16)
    k17=M(text17)
    k18=M(text18)
    print(chr(k0+1072),chr(k1+1072),chr(k2+1072),chr(k3+1072),chr(k4+1072),chr(k5+1072),chr(k6+1072),chr(k7+1072),chr(k8+1072),chr(k9+1072),chr(k10+1072),chr(k11+1072),chr(k12+1072),chr(k13+1072),chr(k14+1072),chr(k15+1072),chr(k16+1072),chr(k17+1072),chr(k18+1072))
    for j in range (len(text18)):
        text=text+chr((ord(text0[j])-1072-k0)%32+1072)
        text=text+chr((ord(text1[j])-1072-k1)%32+1072)
        text=text+chr((ord(text2[j])-1072-k2)%32+1072)
        text=text+chr((ord(text3[j])-1072-k3)%32+1072)
        text=text+chr((ord(text4[j])-1072-k4)%32+1072)
        text=text+chr((ord(text5[j])-1072-k5)%32+1072)
        text=text+chr((ord(text6[j])-1072-k6)%32+1072)
        text=text+chr((ord(text7[j])-1072-k7)%32+1072)
        text=text+chr((ord(text8[j])-1072-k8)%32+1072)
        text=text+chr((ord(text9[j])-1072-k9)%32+1072)
        text=text+chr((ord(text10[j])-1072-k10)%32+1072)
        text=text+chr((ord(text11[j])-1072-k11)%32+1072)
        text=text+chr((ord(text12[j])-1072-k12)%32+1072)
        text=text+chr((ord(text13[j])-1072-k13)%32+1072)
        text=text+chr((ord(text14[j])-1072-k14)%32+1072)
        text=text+chr((ord(text15[j])-1072-k15)%32+1072)
        text=text+chr((ord(text16[j])-1072-k16)%32+1072)
        text=text+chr((ord(text17[j])-1072-k17)%32+1072)
        text=text+chr((ord(text18[j])-1072-k18)%32+1072)
    return text

def Max_Ind(max,arr):
  for i in range (len(arr)):
    if max==arr[i]:
      return i

def long_k(Y):
  K=0
  Long=0
  for i in range (5, 30):
    count=0
    for j in range (len(Y)-i):
      if Y[j]==Y[j+i]:
        count=count+1
    if count>K:
      K=count
      Long=i
    print (count,i)
  return Long

Text_var=open('Var14')
a=str()
for char in Text_var.read():
  a=a+str(char)
print(Indeks(a))

print(reshifr19(a))
print(reshifr91(a))



def reshifr91(Y):
    i=0
    r=20
    text=str()
    text0=str()
    text1=str()
    text2=str()
    text3=str()
    text4=str()
    text5=str()
    text6=str()
    text7=str()
    text8=str()
    text9=str()
    text10=str()
    text11=str()
    text12=str()
    text13=str()
    text14=str()
    text15=str()
    text16=str()
    text17=str()
    text18=str()
    for char in Y:
      if i==1:
        text1=text1+str(char)
      if i==2:
        text2=text2+str(char)
      if i==0:
        text0=text0+str(char)
      if i==3:
        text3=text3+str(char)
      if i==4:
        text4=text4+str(char)
      if i==5:
        text5=text5+str(char)
      if i==6:
        text6=text6+str(char)
      if i==7:
        text7=text7+str(char)
      if i==8:
        text8=text8+str(char)
      if i==9:
        text9=text9+str(char)
      if i==10:
        text10=text10+str(char)
      if i==11:
        text11=text11+str(char)
      if i==12:
        text12=text12+str(char)
      if i==13:
        text13=text13+str(char)
      if i==14:
        text14=text14+str(char)
      if i==15:
        text15=text15+str(char)
      if i==16:
        text16=text16+str(char)
      if i==17:
        text17=text17+str(char)
      if i==18:
        text18=text18+str(char)
      i=i+1
      if i==r:
        i=0
    k0=(Max_Ind(max(count_liters(text0)),count_liters(text0))-14)%32
    k1=(Max_Ind(max(count_liters(text1)),count_liters(text1))-14)%32
    k2=(Max_Ind(max(count_liters(text2)),count_liters(text2))-14)%32
    k3=(Max_Ind(max(count_liters(text3)),count_liters(text3))-14)%32
    k4=(Max_Ind(max(count_liters(text4)),count_liters(text4))-14)%32
    k5=(Max_Ind(max(count_liters(text5)),count_liters(text5))-14)%32
    k6=(Max_Ind(max(count_liters(text6)),count_liters(text6))-14)%32
    k7=(Max_Ind(max(count_liters(text7)),count_liters(text7))-14)%32
    k8=(Max_Ind(max(count_liters(text8)),count_liters(text8))-14)%32
    k9=(Max_Ind(max(count_liters(text9)),count_liters(text9))-14)%32
    k10=(Max_Ind(max(count_liters(text10)),count_liters(text10))-14)%32
    k11=(Max_Ind(max(count_liters(text11)),count_liters(text11))-14)%32
    k12=(Max_Ind(max(count_liters(text12)),count_liters(text12))-14)%32
    k13=(Max_Ind(max(count_liters(text13)),count_liters(text13))-14)%32
    k14=(Max_Ind(max(count_liters(text14)),count_liters(text14))-14)%32
    k15=(Max_Ind(max(count_liters(text15)),count_liters(text15))-14)%32
    k16=(Max_Ind(max(count_liters(text16)),count_liters(text16))-14)%32
    k17=(Max_Ind(max(count_liters(text17)),count_liters(text17))-14)%32
    k18=(Max_Ind(max(count_liters(text18)),count_liters(text18))-14)%32

    
    print(chr(k0+1072),chr(k1+1072),chr(k2+1072),chr(k3+1072),chr(k4+1072),chr(k5+1072),chr(k6+1072),chr(k7+1072),chr(k8+1072),chr(k9+1072),chr(k10+1072),chr(k11+1072),chr(k12+1072),chr(k13+1072),chr(k14+1072),chr(k15+1072),chr(k16+1072),chr(k17+1072),chr(k18+1072))
    for j in range (len(text18)):
        text=text+chr((ord(text0[j])-1072-k0)%32+1072)
        text=text+chr((ord(text1[j])-1072-k1)%32+1072)
        text=text+chr((ord(text2[j])-1072-k2)%32+1072)
        text=text+chr((ord(text3[j])-1072-k3)%32+1072)
        text=text+chr((ord(text4[j])-1072-k4)%32+1072)
        text=text+chr((ord(text5[j])-1072-k5)%32+1072)
        text=text+chr((ord(text6[j])-1072-k6)%32+1072)
        text=text+chr((ord(text7[j])-1072-k7)%32+1072)
        text=text+chr((ord(text8[j])-1072-k8)%32+1072)
        text=text+chr((ord(text9[j])-1072-k9)%32+1072)
        text=text+chr((ord(text10[j])-1072-k10)%32+1072)
        text=text+chr((ord(text11[j])-1072-k11)%32+1072)
        text=text+chr((ord(text12[j])-1072-k12)%32+1072)
        text=text+chr((ord(text13[j])-1072-k13)%32+1072)
        text=text+chr((ord(text14[j])-1072-k14)%32+1072)
        text=text+chr((ord(text15[j])-1072-k15)%32+1072)
        text=text+chr((ord(text16[j])-1072-k16)%32+1072)
        text=text+chr((ord(text17[j])-1072-k17)%32+1072)
        text=text+chr((ord(text18[j])-1072-k18)%32+1072)
    return text

def M(Y):
  v=[ 0 for i in range(32)]
  p=[0.07998,0.01592,0.04533,0.01687,0.02977,0.08496,0.0094,0.01641,0.07367,0.01208,0.03486,0.04343,0.03203,0.067,0.10983,0.02804,0.04746,0.05473,0.06318,0.02615,0.00267,0.00966,0.00486,0.01450,0.00718,0.00361,0.00037,0.01898,0.01735,0.00331,0.006467465030410292,0.02145750195398478 ]
  K=count_liters(Y)
  for j in range(32):
    for i in range(32):
      v[j]=v[j]+p[i]*K[(i+j)%32]
  return Max_Ind(max(v),v)