# -*- coding: utf-8 -*-
"""СК_Лаб1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bph69QWX_QeQBewNXl13s5vxbZO1kbof
"""

def count_liters_and_probels():
  f = open('Text')
  count=[ 0 for i in range(33)]
  for char in f.read():
    if ord(char)>=1072 and ord(char)<=1072+31:
      count[ord(char)-1072]=count[ord(char)-1072]+1
    if ord(char)==32:
      count[32]=count[32]+1
  All=0
  for i in range(33):
    All=All+count[i]
  liters=[ 0 for i in range(33)]
  for i in range(33):
    liters[i]=count[i]
  count.sort(reverse=True)
  for i in range(33):
    for j in range(33):
      if count[i]==liters[j] and j!=32:
        print(chr(j+1072),'=',count[i]/All)
      if count[i]==liters[j] and j==32:
        print('space =',count[i]/All)
  f.close()

def count_liters():
  f = open('Text')
  count=[ 0 for i in range(32)]
  for char in f.read():
    if ord(char)>=1072 and ord(char)<=1072+31:
      count[ord(char)-1072]=count[ord(char)-1072]+1
  All=0
  for i in range(32):
    All=All+count[i]
  liters=[ 0 for i in range(32)]
  for i in range(32):
    liters[i]=count[i]
  count.sort(reverse=True)
  for i in range(32):
    for j in range(32):
      if count[i]==liters[j]:
        print(chr(j+1072),'=',count[i]/All)
  f.close()

def count_bigrams_no_prob():
    f = open('Text')
    import numpy as np
    count=np.array([[ 0.0 for i in range(32)] for i in range(32)])
    a1=0
    a2=0
    a3=0
    first=0
    second=0
    for char in f.read():
      if first==0:
        if ord(char)>=1072 and ord(char)<=1072+31:
          a3=ord(char)-1072
          first =1
      else:
        if ord(char)>=1072 and ord(char)<=1072+31:
          a1=a2
          a2=a3
          a3=ord(char)-1072
          count[a2,a3]=count[a2,a3]+1
          if second==0:
            second =1
          else:
            count[a1,a3]=count[a1,a3]+1
    All=0
    for i in range(32):
      for j in range (32):
        All=All+count[i,j]
    for i in range(32):
      for j in range (32):
        count[i,j]=count[i,j]/All
    print(count)
    f.close()

def count_bigrams_with_prob():
    f = open('Text')
    import numpy as np
    count=np.array([[ 0.0 for i in range(33)] for i in range(33)])
    a1=0
    a2=0
    a3=0
    first=0
    second=0
    for char in f.read():
      if first==0:
        if ord(char)>=1072 and ord(char)<=1072+31:
          a3=ord(char)-1072
          first =1
        if ord(char)==32:
          a3=32
          first =1
      else:
        if ord(char)>=1072 and ord(char)<=1072+31:
          a1=a2
          a2=a3
          a3=ord(char)-1072
          count[a2,a3]=count[a2,a3]+1
          if second==0:
            second =1
          else:
            count[a1,a3]=count[a1,a3]+1
        if ord(char)==32:
          a1=a2
          a2=a3
          a3=32
          count[a2,a3]=count[a2,a3]+1
          if second==0:
            second =1
          else:
            count[a1,a3]=count[a1,a3]+1

    All=0
    for i in range(33):
      for j in range (33):
        All=All+count[i,j]
    for i in range(33):
      for j in range (33):
        count[i,j]=count[i,j]/All
    print(count)
    f.close()

def H1_Pr():
  import math
  f = open('Text')
  H=0
  count=[ 0 for i in range(33)]
  for char in f.read():
    if ord(char)>=1072 and ord(char)<=1072+31:
      count[ord(char)-1072]=count[ord(char)-1072]+1
    if ord(char)==32:
      count[32]=count[32]+1
  All=0
  for i in range(33):
    All=All+count[i]
  for i in range(33):
    count[i]=count[i]/All
    if count[i]!=0:
      H=H-count[i]*math.log2(count[i])
  f.close()
  return H

def H1_No_Pr():
  import math
  f = open('Text')
  H=0
  count=[ 0 for i in range(32)]
  for char in f.read():
    if ord(char)>=1072 and ord(char)<=1072+31:
      count[ord(char)-1072]=count[ord(char)-1072]+1
  All=0
  for i in range(32):
    All=All+count[i]
  for i in range(32):
    count[i]=count[i]/All
    if count[i]!=0:
      H=H-count[i]*math.log2(count[i])
  f.close()
  return H

def H2_No_Pr():
    f = open('Text')
    import numpy as np
    import math
    H=0
    count=np.array([[ 0.0 for i in range(32)] for i in range(32)])
    a1=0
    a2=0
    a3=0
    first=0
    second=0
    for char in f.read():
      if first==0:
        if ord(char)>=1072 and ord(char)<=1072+31:
          a3=ord(char)-1072
          first =1
      else:
        if ord(char)>=1072 and ord(char)<=1072+31:
          a1=a2
          a2=a3
          a3=ord(char)-1072
          count[a2,a3]=count[a2,a3]+1
          if second==0:
            second =1
          else:
            count[a1,a3]=count[a1,a3]+1
    All=0
    for i in range(32):
      for j in range (32):
        All=All+count[i,j]
    for i in range(32):
      for j in range (32):
        count[i,j]=count[i,j]/All
        if count[i,j]!=0:
          H=H-count[i,j]*math.log2(count[i,j])
    H=H/2
    return H
    f.close()

def H2_Pr():
    f = open('Text')
    import numpy as np
    import math
    H=0
    count=np.array([[ 0.0 for i in range(33)] for i in range(33)])
    a1=0
    a2=0
    a3=0
    first=0
    second=0
    for char in f.read():
      if first==0:
        if ord(char)>=1072 and ord(char)<=1072+31:
          a3=ord(char)-1072
          first =1
        if ord(char)==32:
          a3=32
          first =1
      else:
        if ord(char)>=1072 and ord(char)<=1072+31:
          a1=a2
          a2=a3
          a3=ord(char)-1072
          count[a2,a3]=count[a2,a3]+1
          if second==0:
            second =1
          else:
            count[a1,a3]=count[a1,a3]+1
        if ord(char)==32:
          a1=a2
          a2=a3
          a3=32
          count[a2,a3]=count[a2,a3]+1
          if second==0:
            second =1
          else:
            count[a1,a3]=count[a1,a3]+1

    All=0
    for i in range(33):
      for j in range (33):
        All=All+count[i,j]
    for i in range(33):
      for j in range (33):
        count[i,j]=count[i,j]/All
        if count[i,j]!=0:
          H=H-count[i,j]*math.log2(count[i,j])
    H=H/2
    return H
    f.close()

count_liters()

count_liters_and_probels()

count_bigrams_with_prob()

count_bigrams_no_prob()

print('H1 with spaces =',H1_Pr())
print('H1 without spaces =',H1_No_Pr())
print('H2 with spaces =',H2_Pr())
print('H2 without spaces =',H2_No_Pr())